// Fallback mock data in case the server is unavailable
export const mockCarData = [
  {
    id: 1,
    brand: "Maruti Suzuki",
    model: "Swift",
    year: 2023,
    price: 650000,
    fuelType: "Petrol",
    transmission: "Manual",
    engineCapacity: 1197,
    horsepower: 89,
    bodyType: "Hatchback",
    drivetrain: "FWD",
    fuelEfficiency: 23.2,
    imageUrl:
      "https://imgd.aeplcdn.com/664x374/n/cw/ec/126463/swift-exterior-right-front-three-quarter.jpeg?isig=0&q=80",
    description:
      "The new Maruti Suzuki Swift comes with a 1.2L Dualjet petrol engine with idle start-stop technology for better fuel efficiency.",
    color: "Red",
    abs: true,
    ebd: true,
    airbags: "6",
    climateControl: "Automatic",
    sunroof: false,
    ventilatedSeats: false,
    navigationSystem: true,
    smartphoneConnectivity: "Both",
  },
  {
    id: 2,
    brand: "Hyundai",
    model: "Creta",
    year: 2023,
    price: 1200000,
    fuelType: "Diesel",
    transmission: "Automatic",
    engineCapacity: 1493,
    horsepower: 113,
    bodyType: "SUV",
    drivetrain: "FWD",
    fuelEfficiency: 21,
    imageUrl:
      "https://imgd.aeplcdn.com/664x374/n/cw/ec/144861/creta-exterior-right-front-three-quarter.jpeg?isig=0&q=80",
    description:
      "The Hyundai Creta is a compact SUV with premium features like panoramic sunroof, ventilated seats and ADAS technology.",
    color: "White",
    abs: true,
    ebd: true,
    airbags: "6",
    climateControl: "Automatic",
    sunroof: true,
    ventilatedSeats: true,
    navigationSystem: true,
    smartphoneConnectivity: "Both",
  },
  {
    id: 3,
    brand: "Tata",
    model: "Nexon",
    year: 2023,
    price: 800000,
    fuelType: "Petrol",
    transmission: "Manual",
    engineCapacity: 1199,
    horsepower: 118,
    bodyType: "SUV",
    drivetrain: "FWD",
    fuelEfficiency: 17.4,
    imageUrl:
      "https://imgd.aeplcdn.com/664x374/n/cw/ec/141143/nexon-exterior-right-front-three-quarter-3.jpeg?isig=0&q=80",
    description:
      "The Tata Nexon is a compact SUV with a 5-star NCAP safety rating and offers both petrol and diesel engine options.",
    color: "Blue",
    abs: true,
    ebd: true,
    airbags: "6",
    climateControl: "Automatic",
    sunroof: true,
    ventilatedSeats: false,
    navigationSystem: true,
    smartphoneConnectivity: "Both",
  },
  {
    id: 4,
    brand: "Mahindra",
    model: "XUV700",
    year: 2023,
    price: 1500000,
    fuelType: "Diesel",
    transmission: "Automatic",
    engineCapacity: 2198,
    horsepower: 182,
    bodyType: "SUV",
    drivetrain: "AWD",
    fuelEfficiency: 16.1,
    imageUrl:
      "https://imgd.aeplcdn.com/664x374/n/cw/ec/42355/xuv700-exterior-right-front-three-quarter.jpeg?isig=0&q=80",
    description:
      "The Mahindra XUV700 is loaded with features like ADAS, panoramic sunroof, and a powerful mHawk diesel engine.",
    color: "Silver",
    abs: true,
    ebd: true,
    airbags: "7",
    climateControl: "Automatic",
    sunroof: true,
    ventilatedSeats: true,
    navigationSystem: true,
    smartphoneConnectivity: "Both",
    driveModes: "Multiple",
  },
  {
    id: 5,
    brand: "Toyota",
    model: "Fortuner",
    year: 2023,
    price: 3500000,
    fuelType: "Diesel",
    transmission: "Automatic",
    engineCapacity: 2755,
    horsepower: 201,
    bodyType: "SUV",
    drivetrain: "4WD",
    fuelEfficiency: 12.5,
    imageUrl:
      "https://imgd.aeplcdn.com/664x374/n/cw/ec/44709/fortuner-exterior-right-front-three-quarter-19.jpeg?q=80",
    description:
      "The Toyota Fortuner is a premium 7-seater SUV known for its off-road capabilities and reliability.",
    color: "White",
    abs: true,
    ebd: true,
    airbags: "7",
    climateControl: "Automatic",
    sunroof: false,
    ventilatedSeats: true,
    navigationSystem: true,
    smartphoneConnectivity: "Both",
    driveModes: "Multiple",
  },
  {
    id: 6,
    brand: "Honda",
    model: "City",
    year: 2023,
    price: 1100000,
    fuelType: "Petrol",
    transmission: "CVT",
    engineCapacity: 1498,
    horsepower: 119,
    bodyType: "Sedan",
    drivetrain: "FWD",
    fuelEfficiency: 18.4,
    imageUrl:
      "https://imgd.aeplcdn.com/664x374/n/cw/ec/134287/city-exterior-right-front-three-quarter.jpeg?isig=0&q=80",
    description:
      "The Honda City is a premium sedan with a refined 1.5L i-VTEC petrol engine and feature-rich cabin.",
    color: "Black",
    abs: true,
    ebd: true,
    airbags: "6",
    climateControl: "Automatic",
    sunroof: true,
    ventilatedSeats: false,
    navigationSystem: true,
    smartphoneConnectivity: "Both",
  },
  {
    id: 7,
    brand: "Kia",
    model: "Seltos",
    year: 2023,
    price: 1300000,
    fuelType: "Petrol",
    transmission: "DCT",
    engineCapacity: 1353,
    horsepower: 138,
    bodyType: "SUV",
    drivetrain: "FWD",
    fuelEfficiency: 16.8,
    imageUrl:
      "https://imgd.aeplcdn.com/664x374/n/cw/ec/135051/seltos-exterior-right-front-three-quarter.jpeg?isig=0&q=80",
    description:
      "The Kia Seltos offers multiple powertrain options and a host of connected car features.",
    color: "Red",
    abs: true,
    ebd: true,
    airbags: "6",
    climateControl: "Automatic",
    sunroof: true,
    ventilatedSeats: true,
    navigationSystem: true,
    smartphoneConnectivity: "Both",
  },
  {
    id: 8,
    brand: "MG",
    model: "Hector",
    year: 2023,
    price: 1400000,
    fuelType: "Diesel",
    transmission: "Manual",
    engineCapacity: 1956,
    horsepower: 168,
    bodyType: "SUV",
    drivetrain: "FWD",
    fuelEfficiency: 17.4,
    imageUrl:
      "https://imgd.aeplcdn.com/664x374/n/cw/ec/130583/hector-exterior-right-front-three-quarter-2.jpeg?isig=0&q=80",
    description:
      "The MG Hector is known for its large touchscreen infotainment system and voice-controlled features.",
    color: "Grey",
    abs: true,
    ebd: true,
    airbags: "6",
    climateControl: "Automatic",
    sunroof: true,
    ventilatedSeats: false,
    navigationSystem: true,
    smartphoneConnectivity: "Both",
  },
];
